export const globalConfig = {
  date: new Date().toISOString(),
  config: {
    size: "A4",
    usePageNumbers: undefined,
    wrap: {
      work: true,
      education: true,
      volunteer: true,
      projects: true,
      skills: true,
      awards: true,
      certificates: true,
      publications: true,
      languages: true,
      interests: true,
      references: true,
      basics: true,
    },
  },
  strings: {
    work: "Experience",
    volunteer: "Volunteer Experience",
    projects: "Projects",
    education: "Education",
    skills: "Skills",
    awards: "Awards",
    certificates: "Certificates",
    publications: "Publications",
    languages: "Languages",
    interests: "Interests",
    references: "References",
    gpa: "GPA: ",
    untilNow: "Present",
    bullet: "\u2022",
    pageTemplate: "{{pageNumber}}/{{totalPages}}",
  },
};
